"""initial schema

Revision ID: 9c0580ff1f76
Revises: 
Create Date: 2026-05-14 08:46:10.603380+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c0580ff1f76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_external_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('clip','narration','ambient','render')", name='media_assets_kind_chk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_kind_deleted_created', 'media_assets', ['kind', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_media_storage_path', 'media_assets', ['storage_path'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('narration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ambient', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grading', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('render_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latest_render_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_retrieval_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_updated_at', 'projects', ['updated_at'], unique=False)
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('output_asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','rendering','completed','failed')", name='render_jobs_status_chk'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_render_jobs_active', 'render_jobs', ['project_id', 'status'], unique=False)
    op.create_index('ix_render_jobs_project_created', 'render_jobs', ['project_id', 'created_at'], unique=False)
    op.create_table('retrieval_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contemplative_mode', sa.Boolean(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=True),
    sa.Column('per_query', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_sessions_project_created', 'retrieval_sessions', ['project_id', 'created_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_offset', sa.Float(), nullable=False),
    sa.Column('transition_in', sa.String(length=32), nullable=False),
    sa.Column('transition_in_duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('clip','pause')", name='segments_kind_chk'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segments_project_position', 'segments', ['project_id', 'position'], unique=False)
    op.create_table('selected_clips',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('retrieval_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('trim_start', sa.Float(), nullable=True),
    sa.Column('trim_duration', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('imported_asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_session_id'], ['retrieval_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_selected_clips_session', 'selected_clips', ['retrieval_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_selected_clips_session', table_name='selected_clips')
    op.drop_table('selected_clips')
    op.drop_index('ix_segments_project_position', table_name='segments')
    op.drop_table('segments')
    op.drop_index('ix_retrieval_sessions_project_created', table_name='retrieval_sessions')
    op.drop_table('retrieval_sessions')
    op.drop_index('ix_render_jobs_project_created', table_name='render_jobs')
    op.drop_index('ix_render_jobs_active', table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_index('ix_projects_updated_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_media_storage_path', table_name='media_assets')
    op.drop_index('ix_media_kind_deleted_created', table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
